 <link rel="icon" href="https://static.jianshukeji.com/highcharts/images/favicon.ico">
	
	<script src="https://img.hcharts.cn/jquery/jquery-1.8.3.min.js"></script>
	<script src="https://img.hcharts.cn/highcharts/highcharts.js"></script>
	<script src="https://img.hcharts.cn/highcharts/modules/exporting.js"></script>
	<script src="https://img.hcharts.cn/highcharts-plugins/highcharts-zh_CN.js"></script>
	<script>
	(function(a){"object"===typeof module&&module.exports?module.exports=a:a(Highcharts)})(function(a){a.createElement("link",{href:"https://fonts.googleapis.com/css?family\x3dUnica+One",rel:"stylesheet",type:"text/css"},null,document.getElementsByTagName("head")[0]);a.theme={colors:"#2b908f #90ee7e #f45b5b #7798BF #aaeeee #ff0066 #eeaaee #55BF3B #DF5353 #7798BF #aaeeee".split(" "),chart:{backgroundColor:{linearGradient:{x1:0,y1:0,x2:1,y2:1},stops:[[0,"#2a2a2b"],[1,"#3e3e40"]]},style:{fontFamily:"'Unica One', sans-serif"},
plotBorderColor:"#606063"},title:{style:{color:"#E0E0E3",textTransform:"uppercase",fontSize:"20px"}},subtitle:{style:{color:"#E0E0E3",textTransform:"uppercase"}},xAxis:{gridLineColor:"#707073",labels:{style:{color:"#E0E0E3"}},lineColor:"#707073",minorGridLineColor:"#505053",tickColor:"#707073",title:{style:{color:"#A0A0A3"}}},yAxis:{gridLineColor:"#707073",labels:{style:{color:"#E0E0E3"}},lineColor:"#707073",minorGridLineColor:"#505053",tickColor:"#707073",tickWidth:1,title:{style:{color:"#A0A0A3"}}},
tooltip:{backgroundColor:"rgba(0, 0, 0, 0.85)",style:{color:"#F0F0F0"}},plotOptions:{series:{dataLabels:{color:"#B0B0B3"},marker:{lineColor:"#333"}},boxplot:{fillColor:"#505053"},candlestick:{lineColor:"white"},errorbar:{color:"white"}},legend:{itemStyle:{color:"#E0E0E3"},itemHoverStyle:{color:"#FFF"},itemHiddenStyle:{color:"#606063"}},credits:{style:{color:"#666"}},labels:{style:{color:"#707073"}},drilldown:{activeAxisLabelStyle:{color:"#F0F0F3"},activeDataLabelStyle:{color:"#F0F0F3"}},navigation:{buttonOptions:{symbolStroke:"#DDDDDD",
theme:{fill:"#505053"}}},rangeSelector:{buttonTheme:{fill:"#505053",stroke:"#000000",style:{color:"#CCC"},states:{hover:{fill:"#707073",stroke:"#000000",style:{color:"white"}},select:{fill:"#000003",stroke:"#000000",style:{color:"white"}}}},inputBoxBorderColor:"#505053",inputStyle:{backgroundColor:"#333",color:"silver"},labelStyle:{color:"silver"}},navigator:{handles:{backgroundColor:"#666",borderColor:"#AAA"},outlineColor:"#CCC",maskFill:"rgba(255,255,255,0.1)",series:{color:"#7798BF",lineColor:"#A6C7ED"},
xAxis:{gridLineColor:"#505053"}},scrollbar:{barBackgroundColor:"#808083",barBorderColor:"#808083",buttonArrowColor:"#CCC",buttonBackgroundColor:"#606063",buttonBorderColor:"#606063",rifleColor:"#FFF",trackBackgroundColor:"#404043",trackBorderColor:"#404043"},legendBackgroundColor:"rgba(0, 0, 0, 0.5)",background2:"#505053",dataLabelsColor:"#B0B0B3",textColor:"#C0C0C0",contrastTextColor:"#F0F0F3",maskColor:"rgba(255,255,255,0.3)"};a.setOptions(a.theme)});
	</script>	
<!--
*************************************************************************
    Generated by HCODE at 2017-11-18 14:05:21
    From: https://code.hcharts.cn/demos/hhhhxx
*************************************************************************
-->
<div id="container" style="min-width:300px;height:300px"></div>
<?php 
$gg1= json_encode($chart_data_all);
$gg2= json_encode($chart_data_ac);
$ggg1="";
$ggg2="";

for($i=0;$i<strlen($gg1);$i++){
if($gg1[$i]>='0'&&$gg1[$i]<='9'||$gg1[$i]==',')$ggg1.=$gg1[$i];
if($gg2[$i]>='0'&&$gg2[$i]<='9'||$gg2[$i]==',')$ggg2.=$gg2[$i];
}
$times="";
for($i=30;$i>=1;$i--){
$times.="'";
$times.=date('m-d',strtotime("-$i day"));
$times.="'";
$times.=",";
}
$times.="'";
$times.=date('m-d')."'";
?>
	<script>
		//alert((new Date()).getTime();
	$(function () {
		var d1 = <?php echo json_encode($chart_data_all)?>;
		var d2 = <?php echo json_encode($chart_data_ac)?>;
		//alert(d1);
		//document.write(d1);
    $('#container').highcharts({
        chart: {
            type: 'spline'
        },
        title: {
            text: '战况'
        },
		xAxis: {
            categories:[<?php echo $times;?>]
        },
        yAxis: {
            title: {
                text: '次数'
            },
            labels: {
                formatter: function () {
                    return this.value ;
                }
            }
        },
        tooltip: {
            crosshairs: true,
            shared: true
        },
        plotOptions: {
            spline: {
                marker: {
                    radius: 4,
                    lineColor: '#666666',
                    lineWidth: 1
                }
            }
        },
        series: [{
            name: '提交',
            marker: {
                symbol: 'square'
            },
            data:[<?php echo$ggg1; ?>]
        }, {
            name: '正确',
            marker: {
                symbol: 'diamond'
            },
            data: [<?php echo$ggg2; ?>]
        }]
    });
});
</script>

